name: Approval Practice Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a fake build
        run: echo "Building the project..."

  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Awaiting approval
        run: echo "Approve this deployment in the Actions tab to proceed."
        timeout-minutes: 30  # This is the timeout before the job fails
        continue-on-error: true  # Continue the workflow even if the job fails

  deploy:
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
