name: Approval Practice Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a fake build
        run: echo "Building the project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prod  # This is the environment you created
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
