name: Approval Practice Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a fake build
        run: echo "Building the project..."

  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Awaiting approval
        id: approval
        run: |
          echo "Waiting for approval..."
          echo "::set-output name=approved::false"

      - name: Approval step
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build, manual-approval]
    if: ${{ needs.manual-approval.outputs.approved == 'true' }}
    steps:
      - name: Deploy the project
        run: echo "Deploying the project..."
