name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Wait for approval
        run: |
          echo "Deployment is pending approval. Please approve manually."
          sleep 3600  # Wait for 1 hour (adjust as needed)
          echo "Deployment approved."

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: '-avz --delete'
